set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'godlygeek/tabular'
Plugin 'vim-airline'
Plugin 'wikitopian/hardmode'
Plugin 'lambdatoast/elm.vim'
" Plugin 'scrooloose/syntastic'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
set laststatus=2
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line


" hide buffers rather than close them if unsaved changes persist on buffer switch
set hidden

" enable language-specific syntax highlighting
syntax enable

" enable 256 colors
set t_Co=256

" set color theme
colo elflord

" show line numbers
set number

" set tabs to have 4 spaces
set tabstop=4
set softtabstop=4

" when using the >> or << commands, shift lines by 4 spaces
set shiftwidth=4

" search as characters are entered
set incsearch

" highlight matches
set hlsearch

" leader is comma
let mapleader=","

" turn off search highlight
nnoremap <leader><space> :nohlsearch<CR>

"enable folding
set foldenable

" move vertically by visual line
nnoremap j gj
nnoremap k gk

" tabs turn into spaces
set expandtab

" indent when moving to the next line
set autoindent
set pastetoggle=<leader>p

" turn on NERDTree with C-n
map <C-n> :NERDTreeToggle<CR>

" disables Ctrl-z (for Joey)
map <C-z> <Nop>

" toggle hard mode
nnoremap <leader>h <Esc>:call ToggleHardMode()<CR>

" default hard mode on
" autocmd VimEnter,BufNewFile,BufReadPost * silent! call HardMode()

" syntastic configuration
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1 
let g:syntastic_auto_loc_list = 1 
let g:syntastic_check_on_open = 1 
let g:syntastic_check_on_wq = 0 

let g:syntastic_php_checkers=['php','phpcs','phpmd']
let g:syntastic_javascript_checkers = ['jshint']
" let b:syntastic_skip_checks = 0

command! -complete=shellcmd -nargs=+ Shell call s:RunShellCommand(<q-args>)
function! s:RunShellCommand(cmdline)
  echo a:cmdline
  let expanded_cmdline = a:cmdline
  for part in split(a:cmdline, ' ')
     if part[0] =~ '\v[%#<]'
        let expanded_part = fnameescape(expand(part))
        let expanded_cmdline = substitute(expanded_cmdline, part, expanded_part, '')
     endif
  endfor
  botright new
  setlocal buftype=nofile bufhidden=wipe nobuflisted noswapfile nowrap
  call setline(1, 'You entered:    ' . a:cmdline)
  call setline(2, 'Expanded Form:  ' .expanded_cmdline)
  call setline(3,substitute(getline(2),'.','=','g'))
  execute '$read !'. expanded_cmdline
  setlocal nomodifiable
  1
endfunction

map <leader><leader> :w<CR> :Shell ./build --prod<CR> :$<CR><CR>

map <leader>d :bd<CR>

map <leader>e :!./build --prod<CR>

" sane vim window switching (switch vim windows using only Ctrl + h,j,k,l)
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l

" bind jj to Esc only in insert mode
inoremap jj <Esc>
" disable the Esc key in insert mode
inoremap <Esc> <nop>


let g:elm_format_fail_silently = 0

" Elm format
"set autoread
"autocmd BufWritePost *.elm silent !elm-format --yes <afile>
"autocmd BufWritePost *.elm redraw!

" ELM FORMAT ON SAVE
autocmd BufWritePost *.elm call ElmFormat()

" Vim command to format Elm files with elm-format
function! ElmFormat() abort
    " check for elm-format
    if CheckBin('elm-format', 'https://github.com/avh4/elm-format') ==# ''
        return
    endif

    " save cursor position, folds and many other things
    let l:curw = {}
    try
      mkview!
    catch
      let l:curw = winsaveview()
    endtry

    " save our undo file to be restored after we are done.
    let l:tmpundofile = tempname()
    exe 'wundo! ' . l:tmpundofile

    " write current unsaved buffer to a temporary file
    let l:tmpname = tempname() . '.elm'
    call writefile(getline(1, '$'), l:tmpname)

    " call elm-format on the temporary file
    let l:out = system('elm-format ' . l:tmpname . ' --output ' . l:tmpname)

    " if there is no error
    if v:shell_error == 0
        try | silent undojoin | catch | endtry

        " replace current file with temp file, then reload buffer
        let l:old_fileformat = &fileformat
        call rename(l:tmpname, expand('%'))
        silent edit!
        let &fileformat = l:old_fileformat
        let &syntax = &syntax
    elseif g:elm_format_fail_silently == 0
        call EchoLater('EchoError', 'elm-format:', l:out)
    endif

    " save our undo history
    silent! exe 'rundo ' . l:tmpundofile
    call delete(l:tmpundofile)

    " restore our cursor/windows positions, folds, etc..
    if empty(l:curw)
      silent! loadview
    else
      call winrestview(l:curw)
    endif
endf

fun! CheckBin(bin, url) abort
  let l:binpath = substitute(a:bin, '^\s*\(.\{-}\)\s*$', '\1', '')

  if executable(l:binpath)
    return l:binpath
  endif

  call elm#util#EchoWarning('elm-vim:', 'could not find ' . l:binpath . ' [' . a:url . ']')

  return ''
endf

fun! EchoLater(func_name, title, msg) abort
  let s:echo_func_name = a:func_name
  let s:echo_title = a:title
  let s:echo_msg = a:msg
endf

" Disable Arrow keys in Escape mode
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>


" Path to directory in which to save vim sessions
let session_path="~/.vim/sessions/"

" Save vim session with given name
function! s:MakeSession(sessionStr)
    let sessionName=a:sessionStr
    :set sessionoptions=buffers
    exec "mksession " . g:session_path . sessionName . ".vim"
endf

command! -nargs=1 MakeSession call s:MakeSession(<f-args>)

" Load vim session with given name
function! s:LoadSession(sessionStr)
    let sessionName=a:sessionStr
    exec "source " . g:session_path . sessionName . ".vim"
endf

command! -nargs=1 Load call s:LoadSession(<f-args>)

" Automatically save the current session whenever vim is closed
autocmd VimLeave * exec "mksession!" g:session_path . "shutdown_session.vim"

" <F7> restores that 'shutdown session'
noremap <F7> :exe ":source " . g:session_path . "shutdown_session.vim"<CR>
